[package]
name = "smolmsdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ttf-parser"]
ttf-parser = ["dep:ttf-parser"]

[dependencies]
ttf-parser = { version = "0.20.0", optional = true }
